server:
  port: 9093

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookapp
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: BookApp
eureka:
  instance:
    hostname: localhost