spring:
  application:
    name: API-Gateway


  cloud:
    gateway:
      routes:
        - id: StudentService
          uri: lb://StudentApp
          predicates:
            - Path=/student/**
        - id: LibraryService
          uri: lb://LibraryApp
          predicates:
            - Path=/library/**
        - id: BookService
          uri: lb://BookApp
          predicates:
            - Path=/book/**

server:
  port: 9094
eureka:
  instance:
    hostname: localhost


